# Generated by Django 2.2.5 on 2020-11-24 20:19

from django.db import migrations, models
import django.db.models.deletion
import core.choices_array_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(choices=[('SU', 'Start Up'), ('MD', 'Medium'), ('BG', 'Big')], max_length=2)),
                ('company_contact_person', models.CharField(blank=True, max_length=255)),
                ('company_contact_phone', models.CharField(blank=True, max_length=12)),
                ('company_info', models.TextField(blank=True)),
                ('logo_url', models.URLField()),
                ('status', models.CharField(choices=[('DN', 'Did Not Start'), ('ST', 'Started'), ('RJ', 'Rejected'), ('PS', 'Passed')], default=('DN', 'Did Not Start'), max_length=2)),
                ('technology', core.choices_array_field.ChoiceArrayField(base_field=models.CharField(choices=[('NJ', 'Node.js'), ('PY', 'Python'), ('DJ', 'Django'), ('TS', 'TypeScript'), ('RT', 'React'), ('AG', 'Angular'), ('VU', 'Vue.js'), ('SC', 'Scala'), ('AS', 'ASP'), ('GO', 'Go'), ('JQ', 'JQuery'), ('JS', 'JavaScript')], max_length=2), size=None)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('placement_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents_app.PlacementCompanyAgents')),
            ],
            options={
                'db_table': 'Interview',
            },
        ),
    ]
