# Generated by Django 2.2.5 on 2020-11-24 20:19

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementCompanyAgents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placement_company_name', models.CharField(max_length=255)),
                ('agent_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('agent_phone', phone_field.models.PhoneField(blank=True, max_length=31)),
            ],
            options={
                'db_table': 'PlacementCompanyAgents',
                'ordering': ['id'],
            },
        ),
    ]
