# Generated by Django 2.2.5 on 2020-11-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('duration', models.DurationField(blank=True, default=None, null=True)),
                ('meeting_with', models.CharField(max_length=255)),
                ('meeting_content', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='interviews_app.Interview')),
            ],
            options={
                'db_table': 'Processes',
            },
        ),
    ]
